columns {
  type: CATEGORICAL
  name: "type"
  is_manual_type: true
  categorical {
    most_frequent_value: 1
    number_of_unique_values: 55
    items {
      key: "<OOD>"
      value {
        index: 0
        count: 0
      }
    }
    items {
      key: "Apache MD5 Crypt"
      value {
        index: 18
        count: 334
      }
    }
    items {
      key: "Argon2"
      value {
        index: 17
        count: 334
      }
    }
    items {
      key: "Atbash"
      value {
        index: 16
        count: 334
      }
    }
    items {
      key: "Atlassian PBKDF2 SHA1"
      value {
        index: 15
        count: 334
      }
    }
    items {
      key: "BLAKE2b"
      value {
        index: 14
        count: 334
      }
    }
    items {
      key: "BLAKE2s"
      value {
        index: 13
        count: 334
      }
    }
    items {
      key: "Base32"
      value {
        index: 12
        count: 334
      }
    }
    items {
      key: "Base64"
      value {
        index: 11
        count: 334
      }
    }
    items {
      key: "Binary"
      value {
        index: 10
        count: 334
      }
    }
    items {
      key: "CRC-16"
      value {
        index: 9
        count: 334
      }
    }
    items {
      key: "CRC-32"
      value {
        index: 8
        count: 334
      }
    }
    items {
      key: "CRC-64"
      value {
        index: 7
        count: 334
      }
    }
    items {
      key: "Caesar"
      value {
        index: 6
        count: 334
      }
    }
    items {
      key: "Decimal"
      value {
        index: 5
        count: 334
      }
    }
    items {
      key: "HMAC-SHA1"
      value {
        index: 4
        count: 334
      }
    }
    items {
      key: "HMAC-SHA256"
      value {
        index: 53
        count: 333
      }
    }
    items {
      key: "HMAC-SHA512"
      value {
        index: 52
        count: 333
      }
    }
    items {
      key: "Hex"
      value {
        index: 3
        count: 334
      }
    }
    items {
      key: "Keccak-224"
      value {
        index: 51
        count: 333
      }
    }
    items {
      key: "Keccak-256"
      value {
        index: 50
        count: 333
      }
    }
    items {
      key: "Keccak-384"
      value {
        index: 49
        count: 333
      }
    }
    items {
      key: "Keccak-512"
      value {
        index: 48
        count: 333
      }
    }
    items {
      key: "LDAP MD5"
      value {
        index: 47
        count: 333
      }
    }
    items {
      key: "LDAP SHA1"
      value {
        index: 46
        count: 333
      }
    }
    items {
      key: "LDAP salted MD5"
      value {
        index: 45
        count: 333
      }
    }
    items {
      key: "LDAP salted SHA1"
      value {
        index: 44
        count: 333
      }
    }
    items {
      key: "LDAP salted SHA256"
      value {
        index: 43
        count: 333
      }
    }
    items {
      key: "LDAP salted SHA512"
      value {
        index: 42
        count: 333
      }
    }
    items {
      key: "LM"
      value {
        index: 41
        count: 333
      }
    }
    items {
      key: "MD4"
      value {
        index: 40
        count: 333
      }
    }
    items {
      key: "MD5"
      value {
        index: 39
        count: 333
      }
    }
    items {
      key: "NTLM"
      value {
        index: 38
        count: 333
      }
    }
    items {
      key: "PBKDF2-HMAC-SHA256"
      value {
        index: 37
        count: 333
      }
    }
    items {
      key: "PBKDF2-HMAC-SHA512"
      value {
        index: 36
        count: 333
      }
    }
    items {
      key: "PHPass"
      value {
        index: 35
        count: 333
      }
    }
    items {
      key: "ROT13"
      value {
        index: 34
        count: 333
      }
    }
    items {
      key: "ROT47"
      value {
        index: 33
        count: 333
      }
    }
    items {
      key: "SHA1"
      value {
        index: 32
        count: 333
      }
    }
    items {
      key: "SHA224"
      value {
        index: 31
        count: 333
      }
    }
    items {
      key: "SHA256"
      value {
        index: 30
        count: 333
      }
    }
    items {
      key: "SHA3-224"
      value {
        index: 29
        count: 333
      }
    }
    items {
      key: "SHA3-256"
      value {
        index: 28
        count: 333
      }
    }
    items {
      key: "SHA3-384"
      value {
        index: 27
        count: 333
      }
    }
    items {
      key: "SHA3-512"
      value {
        index: 26
        count: 333
      }
    }
    items {
      key: "SHA384"
      value {
        index: 25
        count: 333
      }
    }
    items {
      key: "SHA512"
      value {
        index: 24
        count: 333
      }
    }
    items {
      key: "Vigenere"
      value {
        index: 54
        count: 288
      }
    }
    items {
      key: "bcrypt"
      value {
        index: 2
        count: 334
      }
    }
    items {
      key: "descrypt"
      value {
        index: 1
        count: 334
      }
    }
    items {
      key: "md5crypt"
      value {
        index: 23
        count: 333
      }
    }
    items {
      key: "scrypt"
      value {
        index: 22
        count: 333
      }
    }
    items {
      key: "sha1crypt"
      value {
        index: 21
        count: 333
      }
    }
    items {
      key: "sha256crypt"
      value {
        index: 20
        count: 333
      }
    }
    items {
      key: "sha512crypt"
      value {
        index: 19
        count: 333
      }
    }
  }
}
columns {
  type: CATEGORICAL
  name: "encoded_text"
  is_manual_type: true
  categorical {
    most_frequent_value: 0
    number_of_unique_values: 1
    items {
      key: "<OOD>"
      value {
        index: 0
        count: 17953
      }
    }
  }
}
columns {
  type: CATEGORICAL
  name: "scheme"
  is_manual_type: false
  categorical {
    most_frequent_value: 1
    number_of_unique_values: 18
    items {
      key: "$1$"
      value {
        index: 17
        count: 333
      }
    }
    items {
      key: "$2b$"
      value {
        index: 5
        count: 334
      }
    }
    items {
      key: "$5$"
      value {
        index: 16
        count: 333
      }
    }
    items {
      key: "$6$"
      value {
        index: 15
        count: 333
      }
    }
    items {
      key: "$P$"
      value {
        index: 14
        count: 333
      }
    }
    items {
      key: "$apr1$"
      value {
        index: 4
        count: 334
      }
    }
    items {
      key: "$argon2id$"
      value {
        index: 3
        count: 334
      }
    }
    items {
      key: "$scrypt$"
      value {
        index: 13
        count: 333
      }
    }
    items {
      key: "$sha1$"
      value {
        index: 12
        count: 333
      }
    }
    items {
      key: "<OOD>"
      value {
        index: 0
        count: 0
      }
    }
    items {
      key: "None"
      value {
        index: 1
        count: 12623
      }
    }
    items {
      key: "{MD5}"
      value {
        index: 11
        count: 333
      }
    }
    items {
      key: "{PKCS5S2}"
      value {
        index: 2
        count: 334
      }
    }
    items {
      key: "{SHA}"
      value {
        index: 10
        count: 333
      }
    }
    items {
      key: "{SMD5}"
      value {
        index: 9
        count: 333
      }
    }
    items {
      key: "{SSHA256}"
      value {
        index: 8
        count: 333
      }
    }
    items {
      key: "{SSHA512}"
      value {
        index: 7
        count: 333
      }
    }
    items {
      key: "{SSHA}"
      value {
        index: 6
        count: 333
      }
    }
  }
}
columns {
  type: NUMERICAL
  name: "num_of_chars"
  is_manual_type: false
  numerical {
    mean: 55.204288499025338
    min_value: 3
    max_value: 128
    standard_deviation: 38.394485144943459
  }
}
columns {
  type: NUMERICAL
  name: "contains_bit_only"
  is_manual_type: true
  numerical {
    mean: 0.018880534670008355
    min_value: 0
    max_value: 1
    standard_deviation: 0.13610312296410751
  }
}
columns {
  type: NUMERICAL
  name: "contains_decimal_only"
  is_manual_type: true
  numerical {
    mean: 0.0986911723753829
    min_value: 0
    max_value: 1
    standard_deviation: 0.29824691929767749
  }
}
columns {
  type: NUMERICAL
  name: "contains_hex_only"
  is_manual_type: true
  numerical {
    mean: 0.559676970203286
    min_value: 0
    max_value: 1
    standard_deviation: 0.49642588492881407
  }
}
columns {
  type: NUMERICAL
  name: "contains_alpha_only"
  is_manual_type: true
  numerical {
    mean: 0.072514619883040934
    min_value: 0
    max_value: 1
    standard_deviation: 0.25933809937272817
  }
}
columns {
  type: NUMERICAL
  name: "contains_upper_case_only"
  is_manual_type: true
  numerical {
    mean: 0.033472570314675577
    min_value: 0
    max_value: 1
    standard_deviation: 0.17986705465761282
  }
}
columns {
  type: NUMERICAL
  name: "contains_lower_case_only"
  is_manual_type: true
  numerical {
    mean: 0.53116123642439428
    min_value: 0
    max_value: 1
    standard_deviation: 0.49902803262392287
  }
}
columns {
  type: NUMERICAL
  name: "contains_mixed_upper_lower_case"
  is_manual_type: true
  numerical {
    mean: 0.33400167084377613
    min_value: 0
    max_value: 1
    standard_deviation: 0.47164028105892519
  }
}
columns {
  type: NUMERICAL
  name: "contains_equal"
  is_manual_type: true
  numerical {
    mean: 0.1796157059314954
    min_value: 0
    max_value: 1
    standard_deviation: 0.38386703962990359
  }
}
columns {
  type: NUMERICAL
  name: "contains_slash"
  is_manual_type: true
  numerical {
    mean: 0.15889724310776943
    min_value: 0
    max_value: 1
    standard_deviation: 0.36558023639212206
  }
}
columns {
  type: NUMERICAL
  name: "contains_dot"
  is_manual_type: true
  numerical {
    mean: 0.0785296574770259
    min_value: 0
    max_value: 1
    standard_deviation: 0.26900325346279158
  }
}
columns {
  type: NUMERICAL
  name: "contains_colon"
  is_manual_type: true
  numerical {
    mean: 0.0073517126148705094
    min_value: 0
    max_value: 1
    standard_deviation: 0.085426371434697279
  }
}
columns {
  type: NUMERICAL
  name: "contains_special_chars"
  is_manual_type: true
  numerical {
    mean: 0.34742411584516847
    min_value: 0
    max_value: 1
    standard_deviation: 0.47615186608305071
  }
}
created_num_rows: 17955
